/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import Stera from 'react-native-stera';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    model: 'N/A',
  };
  componentDidMount() {
    Stera.getDeviceName((e, model) => {
      if (e !== null) {
        this.setState({status: e});
        return;
      }
      this.setState({status: 'Started', model});
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Stera☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        {/* <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text> */}
        <Text style={styles.welcome}>☆MODEL☆</Text>
        <Text style={styles.instructions}>{this.state.model}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
